version: "3.8"

services:
  birus:
    build: .
    volumes:
      - ./config.yaml:/config.yaml
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image : mongo
    volumes:
    - ${GOPATH}/src/flavioltonon/birus/.data:/data/db
    ports:
    - 27017:27017
    restart: always