version: "3.8"

services:
  birus:
    build: .
    volumes:
      - ./config.yaml:/config.yaml
    ports:
      - 8000:8000
    depends_on:
      - database
    restart: always

  database:
    image : mongo
    volumes:
    - .data/mongodb:/data/db
    ports:
    - 27017:27017
    restart: always